project:
  type: book

book:
  title: "Data science of JasonLiu"
  author: "Liulinhu"
  date: "2022-9-20"
  search: true
  cover-image: cover.jpg
  page-footer:
    border: false
    background: light
    left: "Copyright 2022, LiuLinhu" 
    right: 
      - icon: github
        href: https://github.com/DrJasonLiu/blogdata
      - icon: twitter 
        href: https://twitter.com/
  navbar:
    background: "#6f60aa"
    foreground: light
    search: true
    pinned: false
    logo: Rlogo.png
    left:
      - text: "Home"
        file: index.qmd
      - text: "R语言"
        file: R语言编程-基于tidyverse.qmd
      - text: "Python"
        file: Python.qmd
      - text: "My notes"
        file: NHANES.qmd
  sidebar: 
    - title: "R语言"
      style: "docked"
      background: light
      contents:
        - R语言编程-基于tidyverse.qmd
        - R机器学习.qmd
        - R数据可视化.qmd
        - 孟德尔随机化.qmd
        - nhanesR.qmd
    - title: "My notes"
      contents: 
        - NHANES.qmd       
    - title: "Python"
      contents: 
        - Python.qmd
  #需要在chapters里添加需要增加的文件不然sidebar里不会有
  chapters:
      - index.qmd
      - R语言编程-基于tidyverse.qmd
      - R机器学习.qmd
      - R数据可视化.qmd
      - nhanesR.qmd
      - 孟德尔随机化.qmd
      - part: "Python"
        chapters: 
          - Python.qmd
      - part: "My notes"
        chapters: 
          - NHANES.qmd

    
comments:
  hypothesis: true
#number-depth: 2
toc-title: "Table of Contents"
bibliography: references.bib
toc: true
#number-sections: true
format:
  html:
    theme: minty
    linkcolor: "#007d65"
    mainfont: "LXGWWenKai-Regular"
    monofont: "LXGWWenKai-Regular"
    toc-depth: 3

editor: visual
reference-location: margin
citation-location: margin
number-sections: false


